# Generated by Django 4.2.7 on 2026-09-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mountains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('height', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
    ]
