# Generated by Django 4.2.7 on 2026-09-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='climbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_event', models.DateTimeField()),
                ('end_event', models.DateTimeField()),
                ('result', models.CharField(choices=[('not_started', 'Не начат'), ('success', 'Успешно'), ('failed', 'Неудача')], default='not_started', max_length=15)),
                ('comment', models.CharField(max_length=200)),
                ('note', models.FloatField(blank=True, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_ascents', to='climbers.groups')),
            ],
        ),
    ]
