# Generated by Django 4.2.7 on 2026-09-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='climbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('sports_category', models.CharField(max_length=10)),
                ('schoole', models.BooleanField()),
                ('test', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_members', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mountain_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_groups', to='mountains.mountains')),
            ],
        ),
        migrations.CreateModel(
            name='climber_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField()),
                ('joined_date', models.DateTimeField()),
                ('climber_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_climber', to='climbers.climbers')),
                ('groups_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_member', to='climbers.groups')),
            ],
        ),
    ]
