# Generated by Django 4.2.7 on 2026-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0002_climbers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
