# Generated by Django 4.2.7 on 2026-09-16 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climbers', '0003_alter_climbers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climber_members',
            name='climber_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='climbers.climbers'),
        ),
        migrations.AlterField(
            model_name='climber_members',
            name='groups_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='climbers.groups'),
        ),
        migrations.AlterField(
            model_name='climber_members',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='climber_members',
            name='role',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='climbers',
            name='schoole',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='climbers',
            name='sports_category',
            field=models.CharField(default='новичок', max_length=10),
        ),
        migrations.AlterField(
            model_name='climbers',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='climbers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='climber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groups',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='groups',
            name='mountain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='mountains.mountains'),
        ),
        migrations.AlterUniqueTogether(
            name='climber_members',
            unique_together={('climber_id', 'groups_id')},
        ),
    ]
